# Generated by Django 5.0.3 on 2024-04-28 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='casinoaffiliate_app.casino')),
            ],
        ),
        migrations.CreateModel(
            name='AdminReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('guarantee_support', models.BooleanField(default=False)),
                ('point', models.FloatField()),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='casinoaffiliate_app.casino')),
            ],
        ),
    ]
