# Generated by Django 5.0.3 on 2024-04-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinoaffiliate_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casino',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
