# Generated by Django 5.0.3 on 2024-05-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinoaffiliate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedeposit',
            name='status',
            field=models.IntegerField(choices=[(1, 'Onaylandı'), (2, 'Onaylanmadı'), (3, 'Beklemede')], default=3),
        ),
        migrations.AlterField(
            model_name='gamewithdrawal',
            name='status',
            field=models.IntegerField(choices=[(1, 'Onaylandı'), (2, 'Onaylanmadı'), (3, 'Beklemede')], default=3),
        ),
    ]
