# Generated by Django 5.0.3 on 2024-05-13 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casinoaffiliate_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamewithdrawal',
            name='user',
        ),
        migrations.DeleteModel(
            name='GameDeposit',
        ),
        migrations.DeleteModel(
            name='GameWithdrawal',
        ),
    ]
