# Generated by Django 5.0.3 on 2024-05-15 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinoaffiliate_app', '0002_alter_gamedeposit_status_alter_gamewithdrawal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameaccount',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 11, 0, 14, 570682)),
        ),
    ]
