# Generated by Django 5.0.3 on 2024-04-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinoaffiliate_app', '0002_casino_url_alter_casino_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
