# Generated by Django 5.0.3 on 2024-04-28 13:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinoaffiliate_app', '0004_alter_casino_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='small_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casino',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
