# Generated by Django 5.0.3 on 2024-04-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinoaffiliate_app', '0005_casino_small_description_alter_casino_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='promo_code',
            field=models.CharField(blank=True, default='-', max_length=50, null=True),
        ),
    ]
