# Generated by Django 5.0.3 on 2024-05-05 18:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casinoaffiliate_app', '0006_bonus_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='cons',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casino',
            name='pros',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
