# Generated by Django 5.0.3 on 2024-05-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinoaffiliate_app', '0007_casino_cons_casino_pros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='cons',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='casino',
            name='pros',
            field=models.TextField(),
        ),
    ]
