# Generated by Django 5.0.3 on 2024-05-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinoaffiliate_app', '0008_alter_casino_cons_alter_casino_pros'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='bonusses',
            field=models.FloatField(blank=True, default=4.95, null=True, verbose_name='Bonus ve Promosyon'),
        ),
        migrations.AddField(
            model_name='casino',
            name='payment_speed',
            field=models.FloatField(blank=True, default=4.95, null=True, verbose_name='Ödeme Hızı'),
        ),
        migrations.AddField(
            model_name='casino',
            name='playable',
            field=models.FloatField(blank=True, default=4.95, null=True, verbose_name='Oynanabilirlik ve Kalite'),
        ),
        migrations.AddField(
            model_name='casino',
            name='reliable',
            field=models.FloatField(blank=True, default=4.95, null=True, verbose_name='Güvenilirlik'),
        ),
        migrations.AddField(
            model_name='casino',
            name='support',
            field=models.FloatField(blank=True, default=4.95, null=True, verbose_name='Destek'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='cons',
            field=models.TextField(blank=True, null=True, verbose_name='Eksiler'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='pros',
            field=models.TextField(blank=True, null=True, verbose_name='Artılar'),
        ),
    ]
