# Generated by Django 5.0.3 on 2024-05-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinoaffiliate_app', '0010_gameaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameaccount',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
