# Generated by Django 5.0.3 on 2024-05-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casinoaffiliate_app', '0011_gameaccount_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
